#!/usr/bin/env Rscript
# Copyright (C) 2021  Jochen Weile, Roth Lab
#
# This file is part of BarseqPro.
#
# BarseqPro is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# BarseqPro is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with BarseqPro.  If not, see <https://www.gnu.org/licenses/>.
options(stringsAsFactors=FALSE)

library(argparser)
library(yogitools)
# library(tileseqMave)
library(hgvsParseR)
library(yogiseq)
library(pbmcapply)

p <- arg_parser(
	"translate library",
	name="pbVarcall_translate.R"
)
p <- add_argument(p, "varcalls", help="variant call file")
# p <- add_argument(p, "parameters", help="parameter json file")
p <- add_argument(p, "cds", help="fasta file containing CDS sequence")
pargs <- parse_args(p)

outfile <- sub("\\.txt$","_transl.csv",pargs$varcalls)
# params <- tileseqMave::parseParameters(pargs$parameters)
cdsFasta <- pargs$cds
cdsSeq <- yogiseq::readFASTA(cdsFasta)[[1]]$toString()

builder <- hgvsParseR::new.hgvs.builder.p(3)
cbuilder <- hgvsParseR::new.hgvs.builder.c()

vc <- read.delim(pargs$varcalls,header=FALSE)
colnames(vc) <- c("barcode","snvs")
out <- yogitools::as.df(pbmclapply(
	vc[,2],
	function(mut) {
		if (mut=="=") {
			list(hgvsc="c.=",hgvsp="p.=",codonChanges="WT",
				codonHGVS="c.=",aaChanges="WT",aaChangeHGVS="p.=")
		} else if (grepl(";",mut)) {
			#Deal with invalid insertions generated by old varcall worker
			if (grepl("ins",mut)) {
				ms <- strsplit(mut,";")[[1]]
				pos <- as.integer(gsub("\\D+","",ms))
				rest <- gsub("\\d+","",ms)
				idx <- grepl("ins",ms)
				ms[idx] <- paste0(pos[idx]-1,"_",pos[idx],rest[idx])
				mut <- paste(ms,collapse=";")
			}
			tileseqMave::translateHGVS(paste0("c.[",mut,"]"),cdsSeq,builder,cbuilder)
		} else {
			if (grepl("ins",mut)) {
				pos <- as.integer(gsub("\\D+","",mut))
				rest <- gsub("\\d+","",mut)
				mut <- paste0(pos-1,"_",pos,rest)
			}
			tileseqMave::translateHGVS(paste0("c.",mut),cdsSeq,builder,cbuilder)
		}
	}
	,mc.cores=8
))

out <- cbind(vc,out)

write.csv(out,outfile,row.names=FALSE)
